version: "3.9"

services:
  nginx:
    build: ./srcs/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
      - nginx/ssl:/etc/nginx/ssl
    restart: always

  wordpress:
    build: ./srcs/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always
    env_file:
      - .env

  mariadb:
    build: ./srcs/mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    env_file:
    - .env

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/
      o: bind

