version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    networks:
      - docker-network
    volumes:
      - wordpress:/var/www/html #change this to /home/jcaro/data:/var/www/html
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    networks:
      - docker-network
    volumes:
      - wordpress:/var/www/html #change this to /home/jcaro/data:/var/www/html
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    networks:
      - docker-network
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    restart: always

networks:
  docker-network:
    driver: bridge
    name: docker-network

volumes:
  wordpress:
  mariadb: