version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    networks:
      - docker-network
    ports:
      - "443:443"
    restart: always
    volumes:
      - wordpress:/var/www/html #change this to /home/jcaro/data:/var/www/html

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - "9000"
    image: wordpress
    networks:
      - docker-network
    restart: always
    volumes:
      - wordpress:/var/www/html #change this to /home/jcaro/data:/var/www/html

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    env_file:
      - .env
    image: mariadb
    networks:
      - docker-network
    restart: always
    volumes:
      - mariadb:/var/lib/mysql

networks:
  docker-network:
    driver: bridge
    name: docker-network

volumes:
  wordpress:
  mariadb: