version: "3.9"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    networks:
      - docker-network
    volumes:
      - wordpress:/var/www/html #change this to /home/jcaro/data:/var/www/html
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    networks:
      - docker-network
    volumes:
      - wordpress:/var/www/html #change this to /home/jcaro/data:/var/www/html
    restart: always
    depends_on:
      - mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB_HOST: ${MYSQL_DB_HOST}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      WP_TITLE: ${WP_TITLE}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_USER_LOGIN: ${WP_USER_LOGIN}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_PASS: ${WP_USER_PASS}

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    networks:
      - docker-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    restart: always

networks:
  docker-network:
    driver: bridge
    name: docker-network

volumes:
  wordpress:
  mariadb: